In [39]:
import torch
from torchvision.ops.boxes import batched_nms
import torch.nn.functional as F

In [50]:
num_classes = 5
num_dets = 3
thr = 0.05
# Suppose its predicted that image has 3 bboxes
scores = torch.randn((num_dets, num_classes)).float().sigmoid()
boxes  = torch.tensor([ [1,2,3,4], [5,6,7,8], [9,10,11,12]] ).float()
labels = torch.arange(num_classes).view(1,-1).expand_as(scores)

print(scores)
print()
print(boxes)
print()
print(labels)

tensor([[0.6956, 0.5182, 0.4894, 0.6956, 0.2929],
        [0.5634, 0.3176, 0.1864, 0.4282, 0.7276],
        [0.6162, 0.3720, 0.6613, 0.2679, 0.4449]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])


In [43]:
keep_idxs = scores > thr
pred_scores = 

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

In [52]:
predicted_prob, topk_idxs = scores.sort(descending=True) # Sort predicitons according to values
print()
print(predicted_prob)
print()
print(topk_idxs)


tensor([[0.6956, 0.6956, 0.5182, 0.4894, 0.2929],
        [0.7276, 0.5634, 0.4282, 0.3176, 0.1864],
        [0.6613, 0.6162, 0.4449, 0.3720, 0.2679]])

tensor([[0, 3, 1, 2, 4],
        [4, 0, 3, 1, 2],
        [2, 0, 4, 1, 3]])


In [53]:
# filter out the proposals with low confidence score
keep_idxs = predicted_prob > thr
predicted_prob = predicted_prob[keep_idxs]
topk_idxs = topk_idxs[keep_idxs]
print(keep_idxs)
print()
print(predicted_prob)
print()
print(topk_idxs)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

tensor([0.6956, 0.6956, 0.5182, 0.4894, 0.2929, 0.7276, 0.5634, 0.4282, 0.3176,
        0.1864, 0.6613, 0.6162, 0.4449, 0.3720, 0.2679])

tensor([0, 3, 1, 2, 4, 4, 0, 3, 1, 2, 2, 0, 4, 1, 3])


In [54]:
anchor_idxs = topk_idxs // num_classes
classes_idxs = topk_idxs % num_classes

anchor_idxs, classes_idxs

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([0, 3, 1, 2, 4, 4, 0, 3, 1, 2, 2, 0, 4, 1, 3]))

In [56]:
bb = boxes[anchor_idxs]

In [59]:
bb.reshape(-1,4)

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [60]:
classes_idxs.reshape(-1)

tensor([0, 3, 1, 2, 4, 4, 0, 3, 1, 2, 2, 0, 4, 1, 3])

In [61]:
classes_idxs.shape, bb.shape

(torch.Size([15]), torch.Size([15, 4]))